### ISSUE TITLE
File readme.md could not be found in your project's workspace

### ISSUE THREAD

**Issue by Scrum** [JasonEtco/actions-toolkit#114]
Tell me why this can happen? try in [https://github.com/inside-demo/actions-demo](https://github.com/inside-demo/actions-demo/runs/533776324?check_suite_focus=true),  [action](https://github.com/Scrum/awesome-readme-to-data-action)

**Comment by JasonEtco** [comment]
You need to checkout the repository in your actions workflow to have access to the repo's files:

```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Awesome readme to data
        uses: Scrum/awesome-readme-to-data-action@v0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
