### ISSUE TITLE
Specify some input or env that allows a user to override the default GITHUB_REPOSITORY env var 

### ISSUE THREAD

**Issue by el-mapache** [JasonEtco/actions-toolkit#146]
**Is your feature request related to a problem? Please describe.**
Using this toolkit and your create-issue action, I am unable to create an issue in a different repository than the action's repo. Our team is attempting to put as much automation in its own repository as possible to separate repo concerns and this functionality would be great!

**Describe the solution you'd like**
I can pass env vars of `repo` and `owner`, or a `repository` value with a `/` delimited string

**Describe alternatives you've considered**
I tried to override the `GITHUB_REPOSITORY` var. Looking at the `Context` class, it does look like process.env.GITHUB_REPOSITORY is checked. Unfortunately, the actions documentation explicitly says that `GITHUB_` variables will be ignored, so I'm not sure how else to proceed.

**Additional context**
I do apologize if I missed a setting somewhere that facilitates this! For context, here is the relevant portion of our action using `create-issue`:
```
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_ISSUE_TOKEN }}
          GITHUB_REPOSITORY: github/heart-services <-- this doesn't get overwritten
          START_DATE: ${{ steps.date.outputs.start }}
          END_DATE: ${{ steps.date.outputs.end }}
          USER_NAME: ${{ steps.get_first_responder.outputs.user }}
          LABELS: first-responder
        with:
          filename: .github/ISSUE_TEMPLATE/first_responder.md
          assignees: ${{ steps.get_first_responder.outputs.user }}
```

Thank you 😄 . Assuming you think this could be a useful feature, I'm happy to open a PR with whatever approach you think is best.
