### ISSUE TITLE
✖  fatal     HttpError: Bad credentials 

### ISSUE THREAD

**Issue by yordis** [JasonEtco/actions-toolkit#79]
I am not sure what I am doing wrong
https://github.com/straw-hat-team/github-actions-workflow/runs/97984058

**Comment by JasonEtco** [comment]
You're using `tools.github` but there's no `GITHUB_TOKEN` to authenticate with. Add `secrets = ["GITHUB_TOKEN]` to the `action "..." {}` block in the `main.workflow`.

**Comment by yordis** [comment]
@JasonEtco I just hardcoded and now I am getting `✖  fatal     HttpError: Not Found`

**Comment by aaomidi** [comment]
I'm getting this error too. 

```
jobs:
  release_labeler:
    name: Auto Merger
    runs-on: ubuntu-latest
    steps:
      - uses: aaomidi/AutoMerge@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

```

```
import { Toolkit } from 'actions-toolkit';
import { Octokit } from '@octokit/rest';

const tools = new Toolkit({
    event: 'issue_comment',
});

tools.command('merge', async (args, match) => {
    const issue = tools.context.payload.issue;
    const sender = tools.context.payload.sender;

    const senderName = sender?.login ?? ' Unknown Sender';
    const issueNumber = issue?.number;

    if (!issueNumber) {
        return tools.log.error('Issue number not defined.');
    }

    const createCommentParams: Octokit.IssuesCreateCommentParams = {
        ...tools.context.repo,
        issue_number: issueNumber,
        body: `Merging PR based on approval from @${senderName}`
    }

    const result = await tools.github.issues.createComment(createCommentParams)

    console.log(result);
});

console.log('Running...')
```

**Comment by aaomidi** [comment]
I solved this problem. I was using `use` instead of `env`

```
name: AutoMerger

on:
  issue_comment:
    types: [created]

jobs:
  release_labeler:
    name: Auto Merger
    runs-on: ubuntu-latest
    steps:
      - uses: aaomidi/AutoMerge@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

```
